name : Build Artifact

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v4.1.1

      - name: Set up Python version
        uses : action/setup-python@main
        with:
          python-version : '3.12'
      
      - name : Create and start virtual enviroment
        run : |
            python -m venv venv
            source venv/bin/activate
        
      - name : Install dependencies
        run : pip install .
        
        # Oryxのbuildのためにrequirements.txtを生成する
      - name : create requirements.txt
        run : pip freeze > requirements.txt
      
      - name : Remove Venv
        run : |
          rm -rf ./venv

      - name : Zip artifact for deployment
        run : zip release.zip ./* -r

      - name : Upload artifact for deployment jobs
        uses : actions/upload-artifact@v3
        with:
          name : python-app
          path : |
            release.zip
            !venv/
